group 'id.laskarmedia.openvpn_flutter'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs project(':openvpn_flutter').file('libs')
        }
    }
}


allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://jitpack.io" }
        flatDir {
            dirs project(':openvpn_flutter').file('libs')
        }
    }
}

apply plugin: 'com.android.library'

android {
    namespace = 'id.laskarmedia.openvpn_flutter'
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }
}

dependencies {
    implementation(name: 'openvpn_library', ext: 'aar')
}
